# FILE ORGANIZATION
obs_dir: 'projects/def-dlafre/fgenest/nirps/WASP-127b/' # starting from projects, home will be added in pipeline

# GLOBAL PARAMETERS USED IN MULTIPLE STAGES
pl_name: 'WASP-127 b'
instrument: 'NIRPS-APERO'
visit_name: 'tr1'

kind_trans: 'transmission'
coeffs: [0.02703969,  1.10037972, -0.96372403,  0.28750393]
ld_model: 'nonlinear'
kind_res: 'high'

# --------------------------------------------------------------------------------------------------
# REDUCTION INPUTS

reduction: 'TEST'
mask_tellu: 0.2
mask_wings: 0.9
n_pc: 5 #[0, 1, 2, 3, 4, 5, 6, 7, 8] # given as a list to test each
iout_all: ['all']
clip_ratio: 6
clip_ts: 6
unberv_it: True

idx_ord: 40 #[15, 33, 41]    # for output plots

del_exposures: null # exposures to delete

# --------------------------------------------------------------------------------------------------
# MODEL INPUTS

run_name: # for file naming?

# mol_species: ['H2O_main_iso', 'CO_all_iso', 'CO2_main_iso',
#              'CH4_Hargreaves_main_iso', 'HCN_main_iso', 'NH3_main_iso',
#              'C2H2_main_iso', 'FeH_main_iso', 'TiO_all_iso', 'OH_SCARLET']  
# mols: ['H2O','CO','CO2','CH4','HCN','NH3','C2H2','FeH','TiO','OH']

# mol_species: ['H20_main_iso']
# mols: ['H2O']

# ---
limP: [-10, 2]    # pressure log range, standard
n_pts: 50         # pressure n_points, standard
mode: 'high' #'lbl      # high resolution spectrum mode
wl_range: [0.9, 1.98] 
chemical_equilibrium: 'True'    # (bool) 
dissociation: "False"             # (bool)
kind_temp: 'iso'             # modif, iso, guillot
line_opacities: ['H2O'] # species, same as mols, add optional dictionary later to give specific linelists to take instead of the automatic one grabbed from starships
opacity_sampling: 1 # downsampling petitRADTRANS resolution, 1=no downsampling, could be 2 for retrievals
continuum_opacities: [] # H- sometimes
other_species: []
# wind: # (bool?) not needed right away
p_cloud: null # unused for now, False by default for now

rot_ker: null # will get code to compare, might not use for default

# parametrization of clouds
gamma_scat: null # no clouds
scat_factor: null # no clouds

C/O: 0.54
Fe/H: 0 # metallicity

fct_star: null # .npz file input with stellar wavelength and flux, implement later
P0: 0.001

T_int: #500.
T_eq: 1200 # only one needed for isothermal profiles
#e-: # electron abundances
#H-: #
tp_alpha: null
tp_delta: null
tp_gamma: null
ptrans: null
kappa_IR: null #10^-3

# organize vars depending on kind_temp

# --------------------------------------------------------------------------------------------------
# CCF INPUTS, more to add after

# for NIRPS, step size of 
RV_range: [-150, 150] # range used to build Kp_array
RV_step: 1 # step size

RV_lim: # used for ttest map
Kp_step: # used for ttest map
# --------------------------------------------------------------------------------------------------
# OTHER PLANET KWARGS
pl_kwargs:
  M_star: null
  R_star: null
  M_pl: null
  R_star: null
  RV_sys: null
  mid_tr: null
  t_peri: null
  transur: null
  period: null
  excent: null
  incl: null
  Teff: null
  A_star: null
  surf_grav: null
  logg: null
  gp: null
  Tp: null
  w: null
  ap: null
  H: null
  sync_equat_rot_speed: null
  trandur: null
