# FILE ORGANIZATION
obs_dir: Path.home() / Path(f'projects/def-dlafre/fgenest/nirps/WASP-127b/')
path_fig:   # path to save figures
# out_dir:    # directory for all outputs, unless we want directories for each step?

# GLOBAL PARAMETERS USED IN MULTIPLE STAGES
pl_name: 'WASP-127 b'
instrument: 'NIRPS-APERO'
visit_name: 'tr1'

kind_trans: 'transmission'
coeffs: [0.02703969,  1.10037972, -0.96372403,  0.28750393]
ld_model: 'nonlinear'
kind_res: 'high'

# --------------------------------------------------------------------------------------------------
# REDUCTION INPUTS
reduction: 'TEST'
mask_tellu: 0.2
mask_wings: 0.9
n_pc: 3
iout_all: ['all']
clip_ratio: 6
clip_ts: 6
unberv_it: True

del_exposures: # exposures to delete

# --------------------------------------------------------------------------------------------------
# MODEL INPUTS

run_name: # for file naming?

mol_species: ['H2O_main_iso', 'CO_all_iso', 'CO2_main_iso',
             'CH4_Hargreaves_main_iso', 'HCN_main_iso', 'NH3_main_iso',
             'C2H2_main_iso', 'FeH_main_iso', 'TiO_all_iso', 'OH_SCARLET']  
mols: ['H2O','CO','CO2','CH4','HCN','NH3','C2H2','FeH','TiO','OH']

# ---
# are the following going to be taken from the planet object?
M_pl:
R_pl:
M_star:
R_star:
P0:
gravity: 
#---

limP: [-10, 2]    # pressure log range
n_pts: 50         # pressure n_points
mode: 'lbl'
wl_range: [0.9, 1.98] 
pressure: 
chemical_equilibrium: # (bool) 
dissociation: # (bool)
kind_temp: # modif, iso, guillot
opacity_sampling:
continuum_opacities:
wind:
p_cloud:
gamma_scat:
scat_factor:
C/O:
Fe/H:
Raf:
atmo_high:
atmo_low:
fct_star:
T_int:
T_eq:
e-:
H:
tp_alpha:
tp_delta: 
tp_gamma:
ptrans:
kappa_IR:

# --------------------------------------------------------------------------------------------------
# CCF INPUTS
n_RV_inj:     # number of points to in RV array to be tested

# --------------------------------------------------------------------------------------------------
# OTHER PLANET KWARGS
RV_sys: None
mid_tr: None
t_peri: None
transur: None
period: None
excent: None
incl: None
Teff: None
A_star: None
surf_grav: None
logg: None
gp: None
Tp: None
w: None
ap: None
H: None
sync_equat_rot_speed: None
trandur: None
M_star: None
R_star: None
M_pl: None
R_star: None